/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerWisataKabBdg;
import javax.swing.JButton;

/**
 *
 * @author Rizky
 */
public class ViewWisataKabBdg extends javax.swing.JFrame {

    /**
     * Creates new form ViewWisataKabBandung
     */
    public ViewWisataKabBdg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnKWisataKabBdg = new javax.swing.JButton();
        btnNonAlamKabBdg = new javax.swing.JButton();
        btnAlamKabBdg = new javax.swing.JButton();
        btnKulinerKabBdg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wisata Kabupaten Bandung");

        btnKWisataKabBdg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKWisataKabBdg.setText("Kembali");
        btnKWisataKabBdg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKWisataKabBdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKWisataKabBdgActionPerformed(evt);
            }
        });

        btnNonAlamKabBdg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNonAlamKabBdg.setText("Wisata non-Alam");
        btnNonAlamKabBdg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNonAlamKabBdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonAlamKabBdgActionPerformed(evt);
            }
        });

        btnAlamKabBdg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlamKabBdg.setText("Wisata Alam");
        btnAlamKabBdg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlamKabBdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlamKabBdgActionPerformed(evt);
            }
        });

        btnKulinerKabBdg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKulinerKabBdg.setText("Wisata Kuliner");
        btnKulinerKabBdg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKulinerKabBdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKulinerKabBdgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnKulinerKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnNonAlamKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnAlamKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKWisataKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKWisataKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNonAlamKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlamKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKulinerKabBdg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKWisataKabBdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKWisataKabBdgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKWisataKabBdgActionPerformed

    private void btnKulinerKabBdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKulinerKabBdgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKulinerKabBdgActionPerformed

    private void btnNonAlamKabBdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonAlamKabBdgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNonAlamKabBdgActionPerformed

    private void btnAlamKabBdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlamKabBdgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlamKabBdgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlamKabBdg;
    private javax.swing.JButton btnKWisataKabBdg;
    private javax.swing.JButton btnKulinerKabBdg;
    private javax.swing.JButton btnNonAlamKabBdg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAlamKabBdg() {
        return btnAlamKabBdg;
    }

    public JButton getBtnKWisataKabBdg() {
        return btnKWisataKabBdg;
    }

    public JButton getBtnKulinerKabBdg() {
        return btnKulinerKabBdg;
    }

    public JButton getBtnNonAlamKabBdg() {
        return btnNonAlamKabBdg;
    }
    
    public void addActionListener(ControllerWisataKabBdg e) {
        btnAlamKabBdg.addActionListener(e);
        btnKulinerKabBdg.addActionListener(e);
        btnNonAlamKabBdg.addActionListener(e);
        btnKWisataKabBdg.addActionListener(e);
    }

    

    
}
