/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerWisataKotaCimahi;
import javax.swing.JButton;

public class ViewWisataKotaCimahi extends javax.swing.JFrame {

    /**
     * Creates new form ViewWisataKotaBandung
     */
    public ViewWisataKotaCimahi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKWisataKotaCimahi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnKulinerKotaCimahi = new javax.swing.JButton();
        btnNonAlamKotaCimahi = new javax.swing.JButton();
        btnAlamKotaCimahi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btnKWisataKotaCimahi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKWisataKotaCimahi.setText("Kembali");
        btnKWisataKotaCimahi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKWisataKotaCimahi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKWisataKotaCimahiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wisata Kota Cimahi");

        btnKulinerKotaCimahi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKulinerKotaCimahi.setText("Wisata Kuliner");
        btnKulinerKotaCimahi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKulinerKotaCimahi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKulinerKotaCimahiActionPerformed(evt);
            }
        });

        btnNonAlamKotaCimahi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNonAlamKotaCimahi.setText("Wisata non-Alam");
        btnNonAlamKotaCimahi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNonAlamKotaCimahi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonAlamKotaCimahiActionPerformed(evt);
            }
        });

        btnAlamKotaCimahi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlamKotaCimahi.setText("Wisata Alam");
        btnAlamKotaCimahi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlamKotaCimahi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlamKotaCimahiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKWisataKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnKulinerKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnNonAlamKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnAlamKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKulinerKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlamKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNonAlamKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnKWisataKotaCimahi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKWisataKotaCimahiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKWisataKotaCimahiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKWisataKotaCimahiActionPerformed

    private void btnKulinerKotaCimahiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKulinerKotaCimahiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKulinerKotaCimahiActionPerformed

    private void btnNonAlamKotaCimahiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonAlamKotaCimahiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNonAlamKotaCimahiActionPerformed

    private void btnAlamKotaCimahiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlamKotaCimahiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlamKotaCimahiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlamKotaCimahi;
    private javax.swing.JButton btnKWisataKotaCimahi;
    private javax.swing.JButton btnKulinerKotaCimahi;
    private javax.swing.JButton btnNonAlamKotaCimahi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAlamKotaCimahi() {
        return btnAlamKotaCimahi;
    }

    public JButton getBtnKWisataKotaCimahi() {
        return btnKWisataKotaCimahi;
    }

    public JButton getBtnKulinerKotaCimahi() {
        return btnKulinerKotaCimahi;
    }

    public JButton getBtnNonAlamKotaCimahi() {
        return btnNonAlamKotaCimahi;
    }
    
    public void addActionListener(ControllerWisataKotaCimahi e) {
        btnKWisataKotaCimahi.addActionListener(e);
        btnKulinerKotaCimahi.addActionListener(e);
        btnNonAlamKotaCimahi.addActionListener(e);
        btnAlamKotaCimahi.addActionListener(e);
        
    }
}
